### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by Obiwarn** [cdimascio/generator-express-no-stress#1]
I cannot get that to run.
When I press the "Try it" button it still asks for user and password.
``` 
securityDefinitions:
   # X-API-Key: abcdef12345
   apiKey:
     type: apiKey
     in: header
     name: X-API-Key

security:
  - apiKey: []
```
BTW: Fantastic project. Thank you!
